.PHONY: clean All

All:
	@echo "----------Building project:[ monotonicArray - Debug ]----------"
	@cd "monotonicArray" && "$(MAKE)" -f  "monotonicArray.mk"
clean:
	@echo "----------Cleaning project:[ monotonicArray - Debug ]----------"
	@cd "monotonicArray" && "$(MAKE)" -f  "monotonicArray.mk" clean
