.PHONY: clean All

All:
	@echo "----------Building project:[ ClassEmployee - Debug ]----------"
	@cd "/home/bal3x/clases/ComputerScience/SP22/CECS222/memoriaDinimica/ClassEmployee" && "$(MAKE)" -f  "ClassEmployee.mk"
clean:
	@echo "----------Cleaning project:[ ClassEmployee - Debug ]----------"
	@cd "/home/bal3x/clases/ComputerScience/SP22/CECS222/memoriaDinimica/ClassEmployee" && "$(MAKE)" -f  "ClassEmployee.mk" clean
