.PHONY: clean All

All:
	@echo "----------Building project:[ Fracciones - Debug ]----------"
	@cd "Fracciones" && "$(MAKE)" -f  "Fracciones.mk"
clean:
	@echo "----------Cleaning project:[ Fracciones - Debug ]----------"
	@cd "Fracciones" && "$(MAKE)" -f  "Fracciones.mk" clean
