.PHONY: clean All

All:
	@echo "----------Building project:[ TeamLeader - Debug ]----------"
	@cd "TeamLeader" && "$(MAKE)" -f  "TeamLeader.mk"
clean:
	@echo "----------Cleaning project:[ TeamLeader - Debug ]----------"
	@cd "TeamLeader" && "$(MAKE)" -f  "TeamLeader.mk" clean
