.PHONY: clean All

All:
	@echo "----------Building project:[ LotteryApplication - Debug ]----------"
	@cd "LotteryApplication" && "$(MAKE)" -f  "LotteryApplication.mk"
clean:
	@echo "----------Cleaning project:[ LotteryApplication - Debug ]----------"
	@cd "LotteryApplication" && "$(MAKE)" -f  "LotteryApplication.mk" clean
