.PHONY: clean All

All:
	@echo "----------Building project:[ Actividad6_2 - Debug ]----------"
	@cd "Actividad6_2" && "$(MAKE)" -f  "Actividad6_2.mk"
clean:
	@echo "----------Cleaning project:[ Actividad6_2 - Debug ]----------"
	@cd "Actividad6_2" && "$(MAKE)" -f  "Actividad6_2.mk" clean
